/**
 * Colunas comuns em exportações de CRMs populares (HubSpot, Pipedrive, RD, Salesforce, Zoho).
 * O importador reconhece automaticamente — não é obrigatório renomear tudo.
 */

export const CONTACT_FIELD_ALIASES = {
  name: [
    "nome",
    "name",
    "contato",
    "contact",
    "full_name",
    "nome_completo",
    "firstname",
    "lastname",
    "first_name",
    "last_name",
    "deal_name",
    "titulo",
    "contact_name",
    "person_name",
    "lead_name",
  ],
  email: [
    "email",
    "e_mail",
    "e-mail",
    "email_address",
    "correo",
    "email_principal",
    "work_email",
  ],
  phone: [
    "telefone",
    "phone",
    "celular",
    "whatsapp",
    "mobile",
    "fone",
    "phone_number",
    "mobilephone",
    "mobile_phone",
    "work_phone",
    "numero",
  ],
  company: [
    "empresa",
    "company",
    "organizacao",
    "organization",
    "razao_social",
    "company_name",
    "account_name",
    "organizacao_nome",
    "associatedcompany",
  ],
  status: [
    "status",
    "estagio",
    "tipo",
    "lifecycle",
    "lifecyclestage",
    "lead_status",
    "contact_status",
  ],
  externalId: [
    "external_id",
    "id_externo",
    "id",
    "crm_id",
    "record_id",
    "contact_id",
    "hs_object_id",
    "deal_id",
  ],
} as const;

export const OPPORTUNITY_FIELD_ALIASES = {
  title: [
    "titulo",
    "title",
    "nome",
    "name",
    "oportunidade",
    "opportunity",
    "negocio",
    "negocio_nome",
    "deal",
    "deal_name",
    "deal_title",
    "assunto",
  ],
  value: [
    "valor",
    "value",
    "amount",
    "deal_value",
    "valor_negocio",
    "montante",
    "preco",
    "ticket",
    "valor_total",
  ],
  status: [
    "status",
    "situacao",
    "deal_status",
    "estado",
    "fase_negocio",
  ],
  stage: [
    "estagio",
    "etapa",
    "stage",
    "deal_stage",
    "fase",
    "coluna",
    "pipeline_stage",
    "funil_etapa",
  ],
  contactName: [
    "contato",
    "contact",
    "contact_name",
    "cliente",
    "nome_contato",
    "person_name",
    "lead_name",
  ],
  contactEmail: [
    "email",
    "contact_email",
    "email_contato",
    "e_mail",
    "e-mail",
    "email_cliente",
  ],
  contactPhone: [
    "telefone",
    "phone",
    "contact_phone",
    "celular",
    "whatsapp",
    "telefone_contato",
    "fone",
  ],
  contactExternalId: [
    "contact_external_id",
    "contact_id",
    "id_contato",
    "cliente_id",
    "person_id",
  ],
  expectedCloseAt: [
    "data_prevista",
    "expected_close_date",
    "close_date",
    "data_fechamento",
    "data_fechamento_prevista",
    "previsao_fechamento",
    "fechamento",
  ],
  notes: [
    "notas",
    "observacoes",
    "observacao",
    "notes",
    "descricao",
    "description",
    "detalhes",
  ],
  externalId: [
    "external_id",
    "id_externo",
    "id",
    "deal_id",
    "crm_id",
    "record_id",
    "opportunity_id",
    "hs_object_id",
  ],
} as const;

export const PRODUCT_FIELD_ALIASES = {
  name: [
    "nome",
    "name",
    "produto",
    "product",
    "titulo",
    "product_name",
    "item",
    "sku_name",
  ],
  price: [
    "preco",
    "price",
    "valor",
    "value",
    "preco_unitario",
    "unit_price",
    "amount",
    "unit_amount",
  ],
  category: ["categoria", "category", "tipo", "product_category", "familia"],
  description: [
    "descricao",
    "description",
    "detalhes",
    "product_description",
    "notes",
  ],
  status: ["status", "situacao", "product_status", "active"],
} as const;
